### ISSUE TITLE
player demon form

### ISSUE THREAD

**Issue by kvonspiczak** [godot-wildlings/gwj7#10]
- [x] idle animation
- [x] walk animation
- [x] run animation
- [x] fireball attack
- [x] spawn bow when talking to anton

**Comment by plexsoup** [comment]
I added the demon form to the existing player.

**Comment by plexsoup** [comment]
I started thinking about spawning the bow after talking to Anton, but it'll be easier just to change his text not to mention the bow.

The problem is, we still have a separate player instance on every level. I haven't had a chance to implement a persistent player object yet.

I changed Anton's text.
